### ISSUE TITLE
change star-icon in choose "My Feed Items"

### ISSUE THREAD

**Issue by prabhakar267** [Swati4star/NSIT-Connect#41]
Number corresponding to the icon represents number of Facebook likes, it should be something related to that instead of stars
@Swati4star

**Comment by Swati4star** [comment]
![screenshot_20161018-222920](https://cloud.githubusercontent.com/assets/9164477/19488127/355cf7e8-9583-11e6-8b6d-69c5af5be459.png)

This icon.

**Comment by GoncaloGarcia** [comment]
I think I can fix this.  Should I just pick an icon or do you have one to replace it with?

**Comment by Swati4star** [comment]
This issue has already been taken care of @GGfpc
Can you look for some other issue
