### ISSUE TITLE
Integrate ButterKnife

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/NSIT-Connect#45]
Integrate butterknife in the code
https://github.com/JakeWharton/butterknife

**Comment by agarwal-akash** [comment]
@Swati4star I am taking this 👍

**Comment by Swati4star** [comment]
Great @agarwal-akash go ahead with this.
If there is some issue, comment here.

**Comment by agarwal-akash** [comment]
@Swati4star hey! I have refactored it completely, can you check it? Also the travis build is still failing

**Comment by Swati4star** [comment]
@agarwal-akash Thanks. I will review in a few days, and will let you know if there are any changes.

**Comment by Swati4star** [comment]
Integrated in 96457edcf840518ecdaf4253a2cef79d60df4915
