### ISSUE TITLE
Team page; static data

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/NSIT-Connect#47]
Move the details of 'About us' page to a json file, and add the data to layouts using that json file.
Add details of members using list view, right now it is static.
Through this, adding of new members will be easier.

**Comment by Kartikdot** [comment]
Is the issue still open ? Can i work on this ?

**Comment by Swati4star** [comment]
yeah sure @Kartik2016 this is still open. Start working on this.
Contact me if you need any help.

**Comment by Kartikdot** [comment]
Thank you. I'll start working on this.

**Comment by Kartikdot** [comment]
Please review the pull request and let me know if any other changes are required.

**Comment by Swati4star** [comment]
So, a few points,
1. why is there a need to change the gradle version? Let them be as it is.
2. Why are you merging other changes here too? there are 115 changed. Why? See to it.

**Comment by Kartikdot** [comment]
Sorry, i messed up a commit i guess. I'll check it again.

**Comment by Kartikdot** [comment]
Android studio reformated the entire code before pushing, hence all the added whitespaces are being counted as changes. Ill correct it and create a new PR.

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/NSIT-Connect/pull/53
Thank you @Kartik2016 👍

**Comment by Kartikdot** [comment]
Pleasure 👍
