### ISSUE TITLE
App crashes when 'View all feed' button is clicked in MY FEED menu

### ISSUE THREAD

**Issue by AtomAgenda** [Swati4star/NSIT-Connect#56]
steps to create the issue : Home->My feed-> checkbox tick on any society-> click on View all feed -> app crashes

after this, even if My feed option is clicked, the app crashes....

Can I resolve this issue @Swati4star ?

**Comment by Swati4star** [comment]
Sure, you can start working on it. 👍

**Comment by AtomAgenda** [comment]
Thank you so much 👍  :)

**Comment by Swati4star** [comment]
Fixed in 96457edcf840518ecdaf4253a2cef79d60df4915
